spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/idgubbug/-GitHub_demo.git
          search-paths: respo
          username: 643051140@qq.com
          password: ..zhang123...

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/